<?php
/**
*/
$cards = $block->getSavedCards();
 ?>
<form action="<?php echo $block->getUrl('Dfe_CheckoutCom/cards/delete', ['_secure' => $this->getRequest()->isSecure()]) ?>" enctype="multipart/form-data" method="post" id="form-checkoutcom-validate">
	<div class="wk-mp-design">
		<fieldset class="fieldset info">
			<legend class="legend">
				<span><?php echo __('Your Saved Cards') ?></span>
			</legend>
			<?php echo $block->getBlockHtml('formkey') ?>
			<?php if($cards){ ?>
					<table cellspacing="0" class="border table">
						<thead>
							<tr>
								<th>
									<?php echo __('Select'); ?>
								</th>
								<th>
									<?php echo __('Cards'); ?>
								</th>
							</tr>
						</thead>		
						<?php foreach($cards as $card){ ?>
							<tr>
								<td>
									<input type="checkbox" class="checkbox" name="card_id[]" value="<?php echo $card->getEntityId(); ?>">
								</td>
								<td>
									<label class="label">
										<?php echo '****'.$card->getData('last4'); ?>
									</label>
								</td>
							</tr>
						<?php } ?>
						<tfoot>
							<tr>
								<td colspan="2">
									<button class="button wk-mp-btn" title="<?php echo __('Delete') ?>" type="submit" id="save_butn">	<span><span><?php echo __('Delete') ?></span></span></button>
								</td>
							</tr>
						</tfoot>
					</table>
					
				<?php }else{ ?>
					<div class="emptymsg">
							<?php echo __('No cards available') ?>
					</div>
				<?php } ?>	
			<div class="buttons-set">
				<p class="back-link">
					<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo __('Back') ?></a>
				</p>
			</div>
		</fieldset>
	</div>
</form>
